#todo check how to use variables
#todo add volume for mongo to not to lost data from previous runs
#todo investigate how to run only your app from idea to  not restart all containers every time
services:
  simple-bank-web-api:
    image: web-api:0.0.1
    build:
      context: ./web-api
      dockerfile: Dockerfile
    #todo check how to configure network instead of links
    links:
      - mongodb-local
    depends_on:
      mongodb-local:
        condition: service_healthy
    ports:
      - "8181:8181"
    environment:
      - SERVER_PORT= 8181
  mongodb-local:
    image: 'mongo:latest'
    container_name: mongodb-local
    environment:
      - 'MONGO_INITDB_DATABASE=simpleBank'
      - 'MONGO_INITDB_ROOT_PASSWORD=simpleBankSecretPassword'
      - 'MONGO_INITDB_ROOT_USERNAME=simpleBankRootUser'
    #todo learn
    ports:
      - '27017:27017'
    #todo learn
    expose:
      - '27017'
    #todo learn
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u simpleBankRootUser -p simpleBankSecretPassword --quiet | grep 1
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
